CREATE DATABASE [TesteTecnicoBernhoeft]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TesteTecnicoBernhoeft', FILENAME = N'C:\TesteTecnico\TesteTecnicoBernhoeft.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TesteTecnicoBernhoeft_log', FILENAME = N'C:\TesteTecnico\TesteTecnicoBernhoeft_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET ARITHABORT OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET  READ_WRITE 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET  MULTI_USER 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TesteTecnicoBernhoeft] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TesteTecnicoBernhoeft]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [TesteTecnicoBernhoeft]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TesteTecnicoBernhoeft] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
